name: Test release
on:
  workflow_dispatch
  #push:
  #  branches:
   #   - master

jobs:
  build:
    name: Build RHEL
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK '7.0.x'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Build
        run: dotnet publish -c Debug -r rhel.9-x64 -p:PublishSingleFile=true --self-contained false -o ./release

      - name: Save output directory as an environment variable
        run: echo "OUTPUT_DIR=./release" >> $GITHUB_ENV
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
           name: published-files
           path: ${{ env.OUTPUT_DIR }}

#      - name: release
#        uses: actions/create-release@v1
#        id: create_release
#        with:
#           draft: false
#           prerelease: false
#           release_name: G9_${{github.run_number}}
#           tag_name: test-${{github.run_number}}
#        env:
#           GITHUB_TOKEN: ${{ secrets.release_token }}
